### ISSUE TITLE
Cannot create 4.8.0 environment in 1.1.1 /1.1.11

### ISSUE THREAD

**Issue by mdathe** [xtuple/xtuple-server#264]
I upgraded my server last week (week of jan 12th) to version 1.1.1 (or 1.1.11 depending on what you execute to determine the version).

I attempt to use Webmin to create a 4.8.0 pilot environment for Enterprise.  The resulting DB appears to 4.7.0.  Logging on through the web client and looking at the settings under Database shows version 4.7.0.

When I attempt to create a 4.8.0 environment from a .backup (using a 4.8.0 masterref DB) it fails altogether.

**Comment by bixwilson** [comment]
I'm working with Tom at the moment. I'll give you a call as soon as I'm 
free.

On 1/19/15 10:00 AM, Mike Atherton wrote:
>
> I upgraded my server last week (week of jan 12th) to version 1.1.1 (or 
> 1.1.11 depending on what you execute to determine the version).
>
> I attempt to use Webmin to create a 4.8.0 pilot environment for 
> Enterprise. The resulting DB appears to 4.7.0. Logging on through the 
> web client and looking at the settings under Database shows version 4.7.0.
>
> When I attempt to create a 4.8.0 environment from a .backup (using a 
> 4.8.0 masterref DB) it fails altogether.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/xtuple/xtuple-server/issues/264>.
>


-- 

BC Wilson
Director of Cloud Services @xTuple
+1-757-461-3022 x110
bc@xTuple.com <mailto:bc@xtuple.com>

xTuple.com <http://www.xtuple.com/> – Download FREE PostBooks ERP, CRM, 
accounting software
xTuple.org <http://www.xtuple.org/> – Contribute to World’s #1 open 
source ERP community
NextBusinessBlog.com <http://www.nextbusinessblog.com/> – Join the 
global innovation conversation

**Comment by bixwilson** [comment]
Mike, what error message do you get on the 480 install?
