### ISSUE TITLE
xtuple-server setup stalls

### ISSUE THREAD

**Issue by samkert** [xtuple/xtuple-server#268]
Hi guys, I'm new to xtuple.  I'm trying to install xtuple postbooks to a spare computer.  First I tried installing xtuple-server on Ubuntu Server 14.04.1 and got stuck at "sudo xtuple-server setup".  Tried installing everything from scratch, still stalls.  Found a post by eric116, he's installing on Ubuntu 12.04, so I tried installing on 12.04.5 Desktop.  Still stalls on xtuple-server setup.

Could anybody help?  Is the issue with xtuple-server code fixed? Or is it just me?

Thanks in advance!

xadmin@servuntu:~$ npm install -fg xtuple-server
npm WARN using --force I sure hope you know what you are doing.
/
> xtuple-server@1.1.11 preinstall /usr/local/lib/node_modules/xtuple-server
> nex do engines

nex info do engines
/usr/local/bin/xtupled -> /usr/local/lib/node_modules/xtuple-server/tasks/sys/service/cli.js

> xtuple-server@1.1.11 postinstall /usr/local/lib/node_modules/xtuple-server
> nex do

nex info do engines
nex info do globalDependencies
info npm install -g ansi2html@^0.0.1
info npm install -g xtuple-server-core@^1.0.0
info npm install -g tasks/sys/service
nex info do linkDependencies
info npm install xtuple-server-sys-cups in tasks/sys/cups
info link /usr/local/lib/node_modules/xtuple-server/node_modules/xtuple-server-sys-cups -> /usr/local/lib/node_modules/xtuple-server/tasks/sys/cups
info npm install xtuple-server-sys-paths in tasks/sys/paths
info link /usr/local/lib/node_modules/xtuple-server/node_modules/xtuple-server-sys-paths -> /usr/local/lib/node_modules/xtuple-server/tasks/sys/paths
info npm install xtuple-server-sys-policy in tasks/sys/policy
info link /usr/local/lib/node_modules/xtuple-server/node_modules/xtuple-server-sys-policy -> /usr/local/lib/node_modules/xtuple-server/tasks/sys/policy
info npm install xtuple-server-sys-service in tasks/sys/service
info link /usr/local/lib/node_modules/xtuple-server/node_modules/xtuple-server-sys-service -> /usr/local/lib/node_modules/xtuple-server/tasks/sys/service
info npm install xtuple-server-sys-ssh in tasks/sys/ssh
info link /usr/local/lib/node_modules/xtuple-server/node_modules/xtuple-server-sys-ssh -> /usr/local/lib/node_modules/xtuple-server/tasks/sys/ssh
info npm install xtuple-server-sys-webmin in tasks/sys/webmin
info link /usr/local/lib/node_modules/xtuple-server/node_modules/xtuple-server-sys-webmin -> /usr/local/lib/node_modules/xtuple-server/tasks/sys/webmin
info npm install xtuple-server-pg-tuner in tasks/pg/tuner
info link /usr/local/lib/node_modules/xtuple-server/node_modules/xtuple-server-pg-tuner -> /usr/local/lib/node_modules/xtuple-server/tasks/pg/tuner
info npm install xtuple-server-pg-snapshotmgr in tasks/pg/snapshotmgr
info link /usr/local/lib/node_modules/xtuple-server/node_modules/xtuple-server-pg-snapshotmgr -> /usr/local/lib/node_modules/xtuple-server/tasks/pg/snapshotmgr
nex info do symlinks
info symlink /usr/local/lib/node_modules/xtuple-server-core/plans/setup.json -> plans/setup.json
info symlink /usr/local/lib/node_modules/xtuple-server-core/plans/install-live.json -> plans/install-live.json
info symlink /usr/local/lib/node_modules/xtuple-server-core/plans/uninstall-live.js -> plans/uninstall-live.js
info symlink /usr/local/lib/node_modules/xtuple-server-core/plans/install-pilot.json -> plans/install-pilot.json
info symlink /usr/local/lib/node_modules/xtuple-server-core/plans/uninstall-pilot.js -> plans/uninstall-pilot.js
info symlink /usr/local/lib/node_modules/xtuple-server-core/plans/backup-database.json -> plans/backup-database.json
info symlink /usr/local/lib/node_modules/xtuple-server-core/plans/copy-database.json -> plans/copy-database.json
info symlink /usr/local/lib/node_modules/xtuple-server-core/plans/drop-database.json -> plans/drop-database.json
info symlink /usr/local/lib/node_modules/xtuple-server-core/plans/rename-database.json -> plans/rename-database.json
info symlink /usr/local/lib/node_modules/xtuple-server-core/plans/restore-database.json -> plans/restore-database.json
info symlink /usr/local/lib/node_modules/xtuple-server-core/plans/import-users.json -> plans/import-users.json
info symlink /usr/local/lib/node_modules/xtuple-server-core/node_modules/xtuple-server-sys-cups -> node_modules/xtuple-server-sys-cups
info symlink /usr/local/lib/node_modules/xtuple-server-core/node_modules/xtuple-server-sys-paths -> node_modules/xtuple-server-sys-paths
info symlink /usr/local/lib/node_modules/xtuple-server-core/node_modules/xtuple-server-sys-policy -> node_modules/xtuple-server-sys-policy
info symlink /usr/local/lib/node_modules/xtuple-server-core/node_modules/xtuple-server-sys-service -> node_modules/xtuple-server-sys-service
info symlink /usr/local/lib/node_modules/xtuple-server-core/node_modules/xtuple-server-sys-ssh -> node_modules/xtuple-server-sys-ssh
info symlink /usr/local/lib/node_modules/xtuple-server-core/node_modules/xtuple-server-sys-webmin -> node_modules/xtuple-server-sys-webmin
info symlink /usr/local/lib/node_modules/xtuple-server-core/node_modules/xtuple-server-pg-snapshotmgr -> node_modules/xtuple-server-pg-snapshotmgr
info symlink /usr/local/lib/node_modules/xtuple-server-core/node_modules/xtuple-server-pg-tuner -> node_modules/xtuple-server-pg-tuner
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data requires github-url-from-git@'~1.1.1' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/github-url-from-git,
npm WARN unmet dependency which is version 1.4.0
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data requires github-url-from-username-repo@'^0.1.0' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/github-url-from-username-repo,
npm WARN unmet dependency which is version 1.0.2
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data requires semver@'2' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/semver,
npm WARN unmet dependency which is version 4.0.0
xtuple-server@1.1.11 /usr/local/lib/node_modules/xtuple-server
├── cp@0.1.1
├── rimraf@2.2.8
├── requireindex@1.1.0
├── lodash@2.4.1
├── github-latest@0.1.2 (semver@1.1.4)
├── npmlog@0.1.1 (ansi@0.3.0)
├── mkdirp@0.5.0 (minimist@0.0.8)
├── pgrep@0.0.5 (bluebird@2.9.1)
├── glob@4.3.5 (inherits@2.0.1, once@1.3.1, inflight@1.0.4, minimatch@2.0.1)
└── xtuple-server-lib@1.2.0 (cron-tab@1.1.16, semver@2.3.2, moment@2.9.0, node-latest-version@1.0.15)
xadmin@servuntu:~$ sudo xtuple-server setup
[sudo] password for xadmin:

**Comment by tjwebb** [comment]
see https://github.com/xtuple/xtuple-server/issues/266

**Comment by tjwebb** [comment]
In #266, the issue was because the wrong version of node was being used. The fix is pending, but in the meantime, ensure that node `0.11.13` is in use by running `n 0.11.13` on the command-line. 

`0.11.14` will *not* work.

**Comment by samkert** [comment]
Awesome, it worked, thank you tjwebb.  


Type n 0.11.13 before running sudo xtuple-server setup.

**Comment by tjwebb** [comment]
@samkert np
