### ISSUE TITLE
Pilot Install Errors new Installation 

### ISSUE THREAD

**Issue by bajajerry** [xtuple/xtuple-server#277]
I have a Ubuntu 14.04.1 LTS box that is being built as dedicated postbooks server;

I have successfully ran:
bootstrap
NPM install
xtuple-server Setup

I am able to get to /webmin from client machine 

I ran the following command from the command line:
sudo xtuple-server intall-pilot --xt-version 4.7.0 --xt-name alpha --xt-quickstart

Here is the log output --- Please HELP trouble starts on line 338 or so.

I have copied entire log file.

0 silly sys.report eachTask
1 verbose xtuple Compiling options for plan: install-pilot
2 silly sys.paths eachTask
3 silly sys.policy eachTask
4 silly pg.cluster eachTask
5 silly nginx.ssl eachTask
6 silly nginx.site eachTask
7 silly nginx.hosts eachTask
8 silly pg.hba eachTask
9 silly pg.tuner eachTask
10 silly pg.config eachTask
11 silly xt.install eachTask
12 silly xt.config eachTask
13 silly xt.database eachTask
14 silly pg.snapshotmgr eachTask
15 silly sys.cups eachTask
16 silly sys.xvfb eachTask
17 silly sys.ssh eachTask
18 silly sys.service eachTask
19 silly sys.report eachTask
20 verbose xtuple Compiling options for plan: rename-database
21 silly xt.database eachTask
22 silly sys.paths eachTask
23 silly pg.config eachTask
24 silly pg.rename eachTask
25 verbose xtuple Compiling options for plan: restore-database
26 silly xt.database eachTask
27 silly sys.paths eachTask
28 silly pg.config eachTask
29 silly pg.restore eachTask
30 verbose xtuple Compiling options for plan: setup
31 silly sys.policy eachTask
32 silly sys.ssh eachTask
33 silly xt.database eachTask
34 silly sys.cups eachTask
35 silly sys.xvfb eachTask
36 silly sys.service eachTask
37 silly sys.webmin eachTask
38 silly sys.report eachTask
39 verbose xtuple Compiling options for plan: uninstall-dev
40 silly local.paths eachTask
41 silly local.policy eachTask
42 silly pg.cluster eachTask
43 silly nginx.ssl eachTask
44 silly nginx.site eachTask
45 silly nginx.hosts eachTask
46 silly pg.hba eachTask
47 silly pg.config eachTask
48 silly xt.install eachTask
49 silly xt.test eachTask
50 silly xt.config eachTask
51 silly xt.database eachTask
52 silly sys.report eachTask
53 verbose xtuple Compiling options for plan: uninstall-live
54 silly sys.paths eachTask
55 silly sys.policy eachTask
56 silly pg.cluster eachTask
57 silly nginx.ssl eachTask
58 silly nginx.site eachTask
59 silly nginx.hosts eachTask
60 silly pg.hba eachTask
61 silly pg.tuner eachTask
62 silly pg.config eachTask
63 silly xt.install eachTask
64 silly xt.config eachTask
65 silly xt.database eachTask
66 silly pg.snapshotmgr eachTask
67 silly sys.cups eachTask
68 silly sys.xvfb eachTask
69 silly sys.ssh eachTask
70 silly sys.service eachTask
71 silly sys.report eachTask
72 verbose xtuple Compiling options for plan: uninstall-pilot
73 silly sys.paths eachTask
74 silly sys.policy eachTask
75 silly pg.cluster eachTask
76 silly nginx.ssl eachTask
77 silly nginx.site eachTask
78 silly nginx.hosts eachTask
79 silly pg.hba eachTask
80 silly pg.tuner eachTask
81 silly pg.config eachTask
82 silly xt.install eachTask
83 silly xt.config eachTask
84 silly xt.database eachTask
85 silly pg.snapshotmgr eachTask
86 silly sys.cups eachTask
87 silly sys.xvfb eachTask
88 silly sys.ssh eachTask
89 silly sys.service eachTask
90 silly sys.report eachTask
91 silly sys.paths eachTask
92 silly sys.policy eachTask
93 silly pg.cluster eachTask
94 silly nginx.ssl eachTask
95 silly nginx.site eachTask
96 silly nginx.hosts eachTask
97 silly pg.hba eachTask
98 silly pg.tuner eachTask
99 silly pg.config eachTask
100 silly xt.install eachTask
101 silly xt.config eachTask
102 silly xt.database eachTask
103 silly pg.snapshotmgr eachTask
104 silly sys.cups eachTask
105 silly sys.xvfb eachTask
106 silly sys.ssh eachTask
107 silly sys.service eachTask
108 silly sys.report eachTask
109 verbose verifyOptions
110 silly sys.paths eachTask
111 silly sys.policy eachTask
112 silly pg.cluster eachTask
113 verbose verifyOptions verifying port
114 verbose pg.cluster Validating Option: port
115 info cmd pg_lsclusters
116 silly cmd attempt 1 of 1
117 silly cmd Ver Cluster Port Status Owner    Data directory               Log file
117 silly cmd 9.3 main    5432 online postgres /var/lib/postgresql/9.3/main /var/log/postgresql/postgresql-9.3-main.log
118 silly nginx.ssl eachTask
119 verbose verifyOptions verifying sslcnames
120 verbose nginx.ssl Validating Option: sslcnames
121 verbose verifyOptions verifying incrt
122 verbose nginx.ssl Validating Option: incrt
123 verbose verifyOptions verifying inkey
124 verbose nginx.ssl Validating Option: inkey
125 silly nginx.site eachTask
126 verbose verifyOptions verifying domain
127 silly nginx.hosts eachTask
128 silly pg.hba eachTask
129 verbose verifyOptions verifying cacrt
130 verbose verifyOptions verifying worldlogin
131 silly pg.tuner eachTask
132 verbose verifyOptions verifying slots
133 verbose verifyOptions verifying capacity
134 silly pg.config eachTask
135 verbose verifyOptions verifying host
136 verbose verifyOptions verifying version
137 verbose verifyOptions verifying locale
138 verbose verifyOptions verifying timezone
139 silly xt.install eachTask
140 verbose verifyOptions verifying ghuser
141 verbose xt.install Validating Option: ghuser
142 verbose verifyOptions verifying ghpass
143 verbose xt.install Validating Option: ghpass
144 silly xt.config eachTask
145 verbose verifyOptions verifying authkey
146 silly xt.database eachTask
147 verbose verifyOptions verifying version
148 verbose xt.database Validating Option: version
149 verbose verifyOptions verifying name
150 verbose xt.database Validating Option: name
151 verbose verifyOptions verifying maindb
152 verbose xt.database Validating Option: maindb
153 verbose verifyOptions verifying edition
154 verbose verifyOptions verifying demo
155 verbose verifyOptions verifying quickstart
156 verbose verifyOptions verifying empty
157 verbose verifyOptions verifying adminpw
158 silly pg.snapshotmgr eachTask
159 verbose verifyOptions verifying snapenable
160 verbose verifyOptions verifying snapschedule
161 verbose pg.snapshotmgr Validating Option: snapschedule
162 verbose verifyOptions verifying snapcount
163 silly sys.cups eachTask
164 silly sys.xvfb eachTask
165 silly sys.ssh eachTask
166 silly sys.service eachTask
167 silly sys.report eachTask
168 verbose xtuple Execution Plan:
169 verbose xtuple [ '{',
169 verbose xtuple   '  "planName": "install-pilot",',
169 verbose xtuple   '  "sys": {},',
169 verbose xtuple   '  "pg": {',
169 verbose xtuple   '    "host": "/var/run/postgresql",',
169 verbose xtuple   '    "version": "9.3",',
169 verbose xtuple   '    "locale": "en_US.UTF-8",',
169 verbose xtuple   '    "timezone": "localtime",',
169 verbose xtuple   '    "snapschedule": "0 2 * * *"',
169 verbose xtuple   '  },',
169 verbose xtuple   '  "nginx": {',
169 verbose xtuple   '    "sslcnames": [',
169 verbose xtuple   '      null',
169 verbose xtuple   '    ],',
169 verbose xtuple   '    "domain": "localhost"',
169 verbose xtuple   '  },',
169 verbose xtuple   '  "xt": {',
169 verbose xtuple   '    "version": "4.7.0",',
169 verbose xtuple   '    "name": "alpha",',
169 verbose xtuple   '    "authkey": "xTuple",',
169 verbose xtuple   '    "edition": "core",',
169 verbose xtuple   '    "gitVersion": "v4.7.0"',
169 verbose xtuple   '  },',
169 verbose xtuple   '  "type": "pilot"',
169 verbose xtuple   '}' ]
170 info xtuple Running plan [install-pilot]...
171 info xtuple Pre-flight checks...
172 silly sys.paths eachTask
173 verbose sys.paths beforeInstall
174 silly sys.policy eachTask
175 verbose sys.policy beforeInstall
176 silly pg.cluster eachTask
177 verbose pg.cluster beforeInstall
178 info cmd pg_lsclusters
179 silly cmd attempt 1 of 1
180 silly cmd Ver Cluster Port Status Owner    Data directory               Log file
180 silly cmd 9.3 main    5432 online postgres /var/lib/postgresql/9.3/main /var/log/postgresql/postgresql-9.3-main.log
181 silly nginx.ssl eachTask
182 verbose nginx.ssl beforeInstall
183 silly nginx.site eachTask
184 verbose nginx.site beforeInstall
185 info cmd service nginx reload
186 silly cmd attempt 1 of 1
187 silly cmd * Reloading nginx configuration nginx
187 silly cmd    ...done.
188 silly nginx.hosts eachTask
189 verbose nginx.hosts beforeInstall
190 silly pg.hba eachTask
191 verbose pg.hba beforeInstall
192 silly pg.tuner eachTask
193 verbose pg.tuner beforeInstall
194 info cmd pg_lsclusters
195 silly cmd attempt 1 of 1
196 silly cmd Ver Cluster Port Status Owner    Data directory               Log file
196 silly cmd 9.3 main    5432 online postgres /var/lib/postgresql/9.3/main /var/log/postgresql/postgresql-9.3-main.log
197 silly pg.config eachTask
198 verbose pg.config beforeInstall
199 silly xt.install eachTask
200 verbose xt.install beforeInstall
201 silly xt.config eachTask
202 verbose xt.config beforeInstall
203 silly xt.database eachTask
204 verbose xt.database beforeInstall
205 silly pg.snapshotmgr eachTask
206 verbose pg.snapshotmgr beforeInstall
207 silly sys.cups eachTask
208 verbose sys.cups beforeInstall
209 silly sys.xvfb eachTask
210 verbose sys.xvfb beforeInstall
211 silly sys.ssh eachTask
212 verbose sys.ssh beforeInstall
213 silly sys.service eachTask
214 verbose sys.service beforeInstall
215 silly sys.report eachTask
216 verbose sys.report beforeInstall
217 silly sys.paths eachTask
218 info sys.paths Running...
219 silly sys.policy eachTask
220 info sys.policy Running...
221 info cmd sleep 1
222 silly cmd attempt 1 of 1
223 silly cmd
224 info cmd openssl rand 6 | base64
225 silly cmd attempt 1 of 1
226 silly cmd Sb+6fbwD
227 info cmd sleep 1
228 silly cmd attempt 1 of 1
229 silly cmd
230 info cmd openssl rand 6 | base64
231 silly cmd attempt 1 of 1
232 silly cmd AjuV+9hK
233 silly pg.cluster eachTask
234 info pg.cluster Running...
235 info cmd pg_createcluster 9.3 alpha-470-pilot --user alpha --socketdir /var/run/postgresql  --start
236 silly cmd attempt 1 of 1
237 silly cmd Creating new cluster 9.3/alpha-470-pilot ...
237 silly cmd   config /etc/postgresql/9.3/alpha-470-pilot
237 silly cmd   data   /var/lib/postgresql/9.3/alpha-470-pilot
237 silly cmd   locale en_US.UTF-8
237 silly cmd   port   5433
238 info cmd sudo -u alpha pg_ctlcluster 9.3 alpha-470-pilot restart -m fast
239 silly cmd attempt 1 of 1
240 silly cmd
241 info cmd sudo -u alpha /usr/lib/postgresql/9.3/bin/createdb alpha -U alpha -O alpha -p 5433
242 silly cmd attempt 1 of 1
243 silly cmd
244 info cmd sudo -u alpha /usr/lib/postgresql/9.3/bin/psql  -U alpha -p 5433 -c "CREATE EXTENSION IF NOT EXISTS plv8;"
245 silly cmd attempt 1 of 1
246 silly cmd CREATE EXTENSION
247 info cmd sudo -u alpha /usr/lib/postgresql/9.3/bin/psql  -U alpha -p 5433 -c "CREATE EXTENSION IF NOT EXISTS plpgsql"
248 silly cmd attempt 1 of 1
249 silly cmd CREATE EXTENSION
250 info cmd sudo -u alpha /usr/lib/postgresql/9.3/bin/psql  -U alpha -p 5433 -c "CREATE EXTENSION IF NOT EXISTS hstore"
251 silly cmd attempt 1 of 1
252 silly cmd CREATE EXTENSION
253 info cmd sudo -u alpha /usr/lib/postgresql/9.3/bin/psql  -U alpha -p 5433 -c "CREATE ROLE admin WITH LOGIN PASSWORD 'AjuV9hK' SUPERUSER"
254 silly cmd attempt 1 of 1
255 silly cmd CREATE ROLE
256 info cmd sudo -u alpha /usr/lib/postgresql/9.3/bin/psql  -U alpha -p 5433 -c "CREATE ROLE xtrole WITH ROLE admin"
257 silly cmd attempt 1 of 1
258 silly cmd CREATE ROLE
259 info cmd sudo -u alpha /usr/lib/postgresql/9.3/bin/psql  -U alpha -p 5433 -c "CREATE ROLE postgres LOGIN SUPERUSER"
260 silly cmd attempt 1 of 1
261 silly cmd CREATE ROLE
262 info cmd sudo -u alpha /usr/lib/postgresql/9.3/bin/psql  -U alpha -p 5433 -c "GRANT xtrole TO admin"
263 silly cmd attempt 1 of 1
264 silly cmd GRANT ROLE
265 info cmd sudo -u alpha /usr/lib/postgresql/9.3/bin/psql  -U alpha -p 5433 -c "GRANT xtrole TO alpha"
266 silly cmd attempt 1 of 1
267 silly cmd GRANT ROLE
268 verbose pg.cluster initCluster [ 'CREATE EXTENSION\n',
268 verbose pg.cluster initCluster   'CREATE EXTENSION\n',
268 verbose pg.cluster initCluster   'CREATE EXTENSION\n',
268 verbose pg.cluster initCluster   'CREATE ROLE\n',
268 verbose pg.cluster initCluster   'CREATE ROLE\n',
268 verbose pg.cluster initCluster   'CREATE ROLE\n',
268 verbose pg.cluster initCluster   'GRANT ROLE\n',
268 verbose pg.cluster initCluster   'GRANT ROLE\n' ]
269 silly nginx.ssl eachTask
270 info nginx.ssl Running...
271 info cmd openssl req -x509 -newkey rsa:2048 -subj '/CN=alpha-470-pilot.localhost' -days 365 -nodes -keyout /etc/xtuple/alpha-470-pilot/ssl/server.key -out /etc/xtuple/alpha-470-pilot/ssl/server.crt
272 silly cmd attempt 1 of 1
273 silly cmd
274 info cmd chown -R alpha /etc/xtuple/alpha-470-pilot/ssl
275 silly cmd attempt 1 of 1
276 silly cmd
277 info cmd chmod -R u=rx /etc/xtuple/alpha-470-pilot/ssl
278 silly cmd attempt 1 of 1
279 silly cmd
280 info cmd openssl x509 -noout -in /etc/xtuple/alpha-470-pilot/ssl/server.crt
281 silly cmd attempt 1 of 1
282 silly cmd
283 info cmd openssl rsa -noout -modulus -in /etc/xtuple/alpha-470-pilot/ssl/server.key
284 silly cmd attempt 1 of 1
285 silly cmd Modulus=A1D964CF5FB07F82E2892CFF08B2B6005B7B8C00A92C571B76985B837D9DE0B2BCE28DBEE652B9800CC1AB6F8ED94A63F989E1E3CC458C3760870F5377AA767B8B2720858BB2E7CF348D9C7C5B2433D1974B1FB92B5AA84F7190D876D55B7A180BAF0778F04DA2AE6507BA49BEA46CCCF65126AE0A2A8324A8B3D3E87C8815622A3089CB220B28289E9540F2D0E06C4EDCA7DA55DEC04164C6DE6F7E8C0A33BABE1260952E8754367169977AE7A0A4611C64349083C67A58C9456F5C2AADF3B95679982C0425A78AC61964E953828E8836CC30BB2F1F20C1D8CB77994CB5C9552DD5BE81C59577FA58D6594AE9C9DCBACA9998D6E37151273CE9C4D4AC09CEDD
286 info cmd openssl x509 -noout -modulus -in /etc/xtuple/alpha-470-pilot/ssl/server.crt
287 silly cmd attempt 1 of 1
288 silly cmd Modulus=A1D964CF5FB07F82E2892CFF08B2B6005B7B8C00A92C571B76985B837D9DE0B2BCE28DBEE652B9800CC1AB6F8ED94A63F989E1E3CC458C3760870F5377AA767B8B2720858BB2E7CF348D9C7C5B2433D1974B1FB92B5AA84F7190D876D55B7A180BAF0778F04DA2AE6507BA49BEA46CCCF65126AE0A2A8324A8B3D3E87C8815622A3089CB220B28289E9540F2D0E06C4EDCA7DA55DEC04164C6DE6F7E8C0A33BABE1260952E8754367169977AE7A0A4611C64349083C67A58C9456F5C2AADF3B95679982C0425A78AC61964E953828E8836CC30BB2F1F20C1D8CB77994CB5C9552DD5BE81C59577FA58D6594AE9C9DCBACA9998D6E37151273CE9C4D4AC09CEDD
289 info cmd chown -R alpha /etc/xtuple/alpha-470-pilot/ssl
290 silly cmd attempt 1 of 1
291 silly cmd
292 silly nginx.site eachTask
293 info nginx.site Running...
294 info cmd ln -s /etc/nginx/sites-available/alpha-470-pilot /etc/nginx/sites-enabled/alpha-470-pilot
295 silly cmd attempt 1 of 1
296 silly cmd
297 info cmd service nginx reload
298 silly cmd attempt 1 of 1
299 silly cmd * Reloading nginx configuration nginx
299 silly cmd    ...done.
300 silly nginx.hosts eachTask
301 info nginx.hosts Running...
302 silly pg.hba eachTask
303 info pg.hba Running...
304 info cmd chown alpha /etc/postgresql/9.3/alpha-470-pilot/pg_hba.conf
305 silly cmd attempt 1 of 1
306 silly cmd
307 info cmd openssl req -new -nodes -keyout /etc/xtuple/alpha-470-pilot/ssl/alpha.key -out /etc/xtuple/alpha-470-pilot/ssl/alpha.csr -subj '/CN=alpha-470-pilot.localhost'
308 silly cmd attempt 1 of 1
309 silly cmd
310 info cmd openssl x509 -req -CAcreateserial -in /etc/xtuple/alpha-470-pilot/ssl/alpha.csr -CAkey /etc/xtuple/alpha-470-pilot/ssl/server.key -CA /etc/xtuple/alpha-470-pilot/ssl/server.crt -out /etc/xtuple/alpha-470-pilot/ssl/alpha.crt
311 silly cmd attempt 1 of 1
312 silly cmd
313 info cmd cp /etc/xtuple/alpha-470-pilot/ssl/server.crt /var/lib/postgresql/9.3/alpha-470-pilot/root.crt
314 silly cmd attempt 1 of 1
315 silly cmd
316 info cmd chown alpha:ssl-cert /var/lib/postgresql/9.3/alpha-470-pilot/root.crt
317 silly cmd attempt 1 of 1
318 silly cmd
319 info cmd chown alpha:alpha /var/lib/postgresql/9.3/alpha-470-pilot/root.crt
320 silly cmd attempt 1 of 1
321 silly cmd
322 info cmd chown alpha:ssl-cert /etc/xtuple/alpha-470-pilot/ssl/alpha.crt
323 silly cmd attempt 1 of 1
324 silly cmd
325 info cmd chown alpha:alpha /etc/xtuple/alpha-470-pilot/ssl/alpha.key
326 silly cmd attempt 1 of 1
327 silly cmd
328 silly pg.tuner eachTask
329 info pg.tuner Running...
330 silly pg.config eachTask
331 info pg.config Running...
332 info cmd sudo -u alpha pg_ctlcluster 9.3 alpha-470-pilot restart -m fast
333 silly cmd attempt 1 of 1
334 silly cmd
335 silly xt.install eachTask
336 info xt.install Running...
337 http xt-install downloading xtuple v4.7.0
338 info cmd git clone --recursive https://github.com/xtuple/xtuple.git /usr/local/xtuple/dist/4.7.0/xtuple
339 silly cmd attempt 1 of 1
340 error cmd failed git clone --recursive https://github.com/xtuple/xtuple.git /usr/local/xtuple/dist/4.7.0/xtuple
341 error cmd status undefined
342 error cmd stdout [undefined]
343 error cmd stderr [undefined]
344 error xtuple Cannot read property 'toString' of null
345 verbose xtuple [ 'TypeError: Cannot read property \'toString\' of null',
345 verbose xtuple   '    at checkExecSyncError (child_process.js:1305:45)',
345 verbose xtuple   '    at execSync (child_process.js:1345:13)',
345 verbose xtuple   '    at Object.module.exports.runCmd (/usr/local/lib/node_modules/xtuple-server-core/node_modules/xtuple-server-lib/util.js:65:54)',
345 verbose xtuple   '    at /usr/local/lib/node_modules/xtuple-server-core/node_modules/xtuple-server-xt-install/index.js:73:18',
345 verbose xtuple   '    at Function.forEach (/usr/local/lib/node_modules/xtuple-server-core/node_modules/lodash/dist/lodash.js:3297:15)',
345 verbose xtuple   '    at Object._.extend.executeTask (/usr/local/lib/node_modules/xtuple-server-core/node_modules/xtuple-server-xt-install/index.js:61:7)',
345 verbose xtuple   '    at /usr/local/lib/node_modules/xtuple-server-core/index.js:47:12',
345 verbose xtuple   '    at /usr/local/lib/node_modules/xtuple-server-core/node_modules/xtuple-server-lib/util.js:93:16',
345 verbose xtuple   '    at Function.forEach (/usr/local/lib/node_modules/xtuple-server-core/node_modules/lodash/dist/lodash.js:3297:15)',
345 verbose xtuple   '    at /usr/local/lib/node_modules/xtuple-server-core/node_modules/xtuple-server-lib/util.js:91:9',
345 verbose xtuple   '    at Function.forEach (/usr/local/lib/node_modules/xtuple-server-core/node_modules/lodash/dist/lodash.js:3297:15)',
345 verbose xtuple   '    at Object.module.exports.eachTask (/usr/local/lib/node_modules/xtuple-server-core/node_modules/xtuple-server-lib/util.js:90:7)',
345 verbose xtuple   '    at executePlan (/usr/local/lib/node_modules/xtuple-server-core/index.js:41:12)',
345 verbose xtuple   '    at /usr/local/lib/node_modules/xtuple-server-core/index.js:116:9',
345 verbose xtuple   '    at Object.module.exports.execute (/usr/local/lib/node_modules/xtuple-server-core/index.js:114:12)',
345 verbose xtuple   '    at executePlan (/usr/local/lib/node_modules/xtuple-server-core/cli.js:49:11)' ]
346 info xtuple Please see xtuple-server.log for more info

**Comment by gilmoskowitz** [comment]
@bajajerry - What do you see in `/usr/local/xtuple/dist/4.7.0/xtuple`? That directory should exist and contain about 15 files and subdirectories. In the `package.json` file, line ~5 should say something like `"version": "4.7.0",`

If the directory is not complete or the version number in the package.json is not 4.7.0, delete `/usr/local/xtuple/dist/4.7.0/xtuple` and its contents. Then clean up any trash that might have been left behind by the failed `install-pilot` and try the `install-pilot` again:
```
$ sudo xtuple-server uninstall-pilot --xt-name alpha
$ sudo xtuple-server install-pilot --xt-version 4.7.0 --xt-name alpha --xt-quickstart
```

You should be able to use `--xt-version 4.8.1` if you want something newer to work with.

**Comment by bajajerry** [comment]
This worked I am now logged on from client machine on v 4.8.1 
Thanks Mucho
