### ISSUE TITLE
Connect with desktop client

### ISSUE THREAD

**Issue by kb5zlr** [xtuple/xtuple-server#278]
This may be one of those obvious things I am overlooking, but I have installed xtuple postbooks pilot on a Ubuntu server several times now. However with each installation I end up wiping everything clean and restarting. I am always able to connect via html interface on port 41212. But every time I try to connect with desktop client I cannot get past ssl certificate error. Surely it should not be so difficult to connect with the client. What am I missing? I have tried with Windows 7 and OS X clients and have problems with both. Error is no certificate found in /Users/#####/.postrgesql/*.crt

**Comment by tjwebb** [comment]
> Error is no certificate found in /Users/#####/.postrgesql/*.crt

Did you really see this error on Windows? I find it believable for OSX. @bixwilson didn't you see this one time?

**Comment by kb5zlr** [comment]
Not exact same error on Windows of course, but same general idea. Cannot connect desktop client due to ssl error. (But can login via html port 41212 on Windows). Thanks.

**Comment by bixwilson** [comment]
When signing in with the desktop, make sure to use the internal IP address rather than the domain. For example, if you were using the demo virtual machine, the IP is 192.168.33.10. More here: https://github.com/xtuple/xtuple-server/wiki/xTuple-Desktop-Client

**Comment by kb5zlr** [comment]
I have been. In this case it is not a virtual machine, it is a linux box running Ubuntu 14.01 and I have installed everything per the quick start. The internal network IP is 192.168.1.158 and that is what I have been trying to connect to. I have tried 5 different installations over a period of about 2 weeks and have the same issue with each one.

**Comment by tjwebb** [comment]
> Error is no certificate found in /Users/#####/.postrgesql/*.crt

I just have no idea why the client would be looking for this file. Can you post the pg_hba.conf file from the ? Can you connect via pgAdmin?

**Comment by kb5zlr** [comment]
Hello again.
Yes, I can login over the LAN via pdAdmin to the xtuple server so a connection is possible. No Postgres installations on client machines. Here is the pg_hba file. I have not done any modification of any settings:

# DO NOT DISABLE!
# If you change this first entry you will need to make sure that the
# database superuser can access the database using some other method.
# Noninteractive access to all databases is required during automatic
# maintenance (custom daily cronjobs, replication, and similar tasks).
#
# Database administrative login by Unix domain socket
local   all             alpha                               peer

# TYPE  DATABASE        USER            ADDRESS                 METHOD

# "local" is for Unix domain socket connections only
local   all             all                                     trust
# IPv4 local connections:
host    all             all             127.0.0.1/32            md5
# IPv6 local connections:
host    all             all             ::1/128                 md5
# Allow replication connections from localhost, by a user with the
# replication privilege.
#local   replication     postgres                                peer
#host    replication     postgres        127.0.0.1/32            md5
#host    replication     postgres        ::1/128                 md5

# internal networks (rfc1918); don't require ssl
host       all             all             10.0.0.0/8              md5
host       all             all             172.16.0.0/12           md5
host       all             all             192.168.0.0/16          md5

# allow "alpha" user access from anywhere, but require matching ssl
# cert for this privilege to even be considered.
# hostssl    all             alpha       0.0.0.0/0               cert clientcert=1

# world
#hostssl    all             all             0.0.0.0/0               md5

**Comment by tjwebb** [comment]
> hostssl all alpha 0.0.0.0/0 cert clientcert=1

Can you try commenting out that line?

Also can you please wrap your code in a code block e.g.
```
I am code
```

**Comment by tjwebb** [comment]
Also can you copy/paste the exact info you're putting into the xtuple login form? (except password)

**Comment by kb5zlr** [comment]
I commented out the hostssl line and restarted entire sever (not just postgresql). No change on client login error.
For login I am using:
Username: admin
Password: ********
Server: 192.168.1.158
Port: 5433
Database: alpha-470-pilot

**Comment by tjwebb** [comment]
What version of the desktop client are you using? 4.7?

Besides that I'm out of ideas. I don't recall seeing this error before and I don't know what else the issue could be. Perhaps someone at xTuple could help you out...

**Comment by kb5zlr** [comment]
It is version 4.8. Well thanks for trying.

**Comment by tjwebb** [comment]
You installed a 4.7.0 database, so you should use client version 4.7.

**Comment by kb5zlr** [comment]
Just downloaded 4.7 client. Same certificate error. At this point I think I will just give up on the Linux installation and try doing an install on mac. Might have better luck. Thanks for your help.

**Comment by gilmoskowitz** [comment]
@kb5zlr - I tried several times today to replicate the problem you see. So far no success. I'll keep trying and let you know if I learn anything useful.

If pgAdmin can connect to the database over the network, a PostBooks client running on that same machine should be able to connect without trouble. This is the first time I've heard of a missing certificate error connecting to the database server, but then we never use the client certificate method. There might be a conflict between the `cert` authentication method and supplying a password, too. You can try starting the desktop client from the command line like so:
```
$ .../xtuple --databaseURL=psql://hostname:port/databaseName --username=userName --noAuth
```
and see if the error occurs.

Dumb question - do you actually have a client certificate installed?

**Comment by kb5zlr** [comment]
I do not have a client certificate installed. I hope I don't have to as it would be a pain to do that on various computers we hope to use as clients. Thinking that this might somehow be a hardware problem, I created a new ubuntu virtual machine in Parallels with ubuntu 14.01. I then did the QuickStart steps including installation of alpha pilot exactly per the instructions....again I can access from pgAdmin and can access the server via html on port 41212, but I still get a certificate missing error on each machine I try to login on via the client (2 different Macs and 2 different PCs using client 4.8 on 2 of the machines and client 4.7 on 2 of the machines). I am stumped.

**Comment by tjwebb** [comment]
Do you have a proxy server or firewall on your network that does packet
filtering? This is just something that has always worked, and we've never
seen this issue. I think it must either be a network issue, or a
side-effect of some configuration of the client machines on this particular
network.

**Comment by bixwilson** [comment]
@kb5zlr , I see you installed Ubuntu 14.01. Don't we recommend Ubuntu 14.04? Please see: https://github.com/xtuple/xtuple-server/wiki/Steps-to-Install-Ubuntu

**Comment by tjwebb** [comment]
Yea, Ubuntu 12.04 or Ubuntu 14.04.

**Comment by kb5zlr** [comment]
Okay, taking your suggestions, I rebuilt the ubuntu server again using 14.04. I also took it off of our internal LAN running on sonicwall router and placed it on an entirely separate LAN that we maintain for the VOIP phones (linksys router) to eliminate any issue with the network hardware. Exact same issue still occurs. /Users/#####/.postgresql/postgresql.crt. Also tried with Windows client just to be sure, but could not log in there either. Can login via pdAdmin though and via HTML port 41212 though.

**Comment by xtpclark** [comment]
Hello,

Are you running the client from within the .zip file, or have you extracted it?
And why is this Mac/OSX path being complained about? -> Users/#####/.postgresql/postgresql.crt 

Thanks,

Perry Clark
xTuple

**Comment by kb5zlr** [comment]
The client has been installed using the .dmg installer on mac or installer on Windows. This is the whole question. Why is xtuple insisting there be a certificate installed on the mac or windows machine? The client refuses to connect saying that no certificate is found on the client machine. I have been told that there is no reason the client should be asking for that certificate if the alpha demo is installed.

**Comment by tjwebb** [comment]
> Why is xtuple insisting there be a certificate installed on the mac or
windows machine?

There isn't. None of this makes any sense.

Can you take a screenshot of the error message?

**Comment by kb5zlr** [comment]
![screen shot 2015-02-17 at 5 17 56 pm](https://cloud.githubusercontent.com/assets/11018581/6238434/06473832-b6c9-11e4-83de-dbf152e37cec.png)

**Comment by kb5zlr** [comment]
Here is my login:
![screen shot 2015-02-17 at 5 20 22 pm](https://cloud.githubusercontent.com/assets/11018581/6238486/59ad9048-b6c9-11e4-9512-b035b626809f.png)

**Comment by tjwebb** [comment]
Dude, seriously? This whole time we go on this wild goose chase for you, and you don't even take an extra 10 seconds to write out the full error message. It clearly says:

# password authentication failed for user "admin"

xtuple can take it from here. I'm not spending any more time on this.

**Comment by kb5zlr** [comment]
Don't jump the gun. I am using the password exactly as given to me by the install. The password functions for pgAdmin and it functions for HTML login.

**Comment by tjwebb** [comment]
> It's only trying to open that file as a last resort effort to authenticate you, because your password isn't working. This is because your authkey on the server doesn't match the client.

**Comment by kb5zlr** [comment]
This is the install. I am using the password as given:
![img_0514](https://cloud.githubusercontent.com/assets/11018581/6238612/94c7efc4-b6ca-11e4-9fa0-e5dc761ea342.JPG)

**Comment by tjwebb** [comment]
You're missing the point and you're not listening. I know you're typing in the password correct. That doesn't matter. You need to set the server's authkey to match your client. If you don't know what that means, then contact support.

**Comment by kb5zlr** [comment]
Okay. Thanks. Shouldn't that be made clear somewhere in the starter instructions? I will figure it out. Thanks for your help.

**Comment by gilmoskowitz** [comment]
@kb5zlr - I've reproduced the failure connecting from a Mac client.

The exact same message appears whether I type the wrong database name or the wrong password or the wrong username. I can successfully log in if all three are correct. Like you, I have no client certificate installed on my Mac.

The tricky part was getting the database name correct. In my case it was `demo_pilot`, not `alpha-481-pilot` as the xtuple-server command output would suggest. I've entered issue #279 for this.

**Comment by kb5zlr** [comment]
Thank you very much....that was the problem. I had tried every combo I could think of including demo-pilot. But as soon as I entered demo_pilot the client launched without issue. I appreciate the follow up.

**Comment by mperreault1980** [comment]
I'm having the same issue with a quickstart live version. How do I find what the right Db name is?

**Comment by mperreault1980** [comment]
N/m. Figured it out.

**Comment by kinnvest** [comment]
Hi I am having an error trying to connect please find screenshot...
![image](https://cloud.githubusercontent.com/assets/12329517/7534387/66f601d2-f57a-11e4-930c-2d40c66d9e5a.png)
please help

**Comment by gilmoskowitz** [comment]
@kinnvest -

There are a few options:

- Connect to that database server with pgAdmin and look at the database names
- Use the webmin interface to the database server
- Connect with `psql` from the command line to a database named `template1`, then use `\l` (backslash then lower-case letter L) to list the databases:
```
    $ psql -h ip.address.of.dbserver -p 5433 -U admin -d template1
    password: thePasswordXtupleServerGaveYou
    > \l
   [ list of databases ]
```

Meanwhile, I'll publish the fix for #279 to avoid problems like this in the future.

**Comment by kinnvest** [comment]
@gilmoskowitz 

It wont allow me to login it gives the same error of no config pg_hba.conf..i am really stressed...

**Comment by gilmoskowitz** [comment]
@kinnvest - What methods have you tried to learn the name of the database? What errors do you get from pgAdmin, psql, webmin, etc.?

**Comment by kinnvest** [comment]
I am trying to login into my server at 41.185.27.28.I tried to login in 
via psql and it gave me the same error of no pg_hba config.

-- 
Mark Kinnear IChief Revenue Officer I National
*Kinnvest *
(o) 011 057-3652 (c) 063 098 8963
(e) mark@kinnvest.com (w) www.kinnvest.com
*"Dream,Believe & Achieve"**

*
This email and attachments are confidential and may be legally 
privileged or otherwise exempt from disclosure. If you are not the 
intended recipient, any unauthorized use, dissemination, distribution or 
reproduction of this message is strictly prohibited. If this e-mail is 
received in error, please delete immediately from your system 
*________________________________________________________________________________________________________________________________________________________________________________________________*

**Comment by gilmoskowitz** [comment]
What database are you trying to log in to? Since you don't know the name of the xTuple database, try one you know should exist like `template1`.

**Comment by kinnvest** [comment]
Hi Gil

I am still getting the same error.When I log into my xtuple on the web I 
use a user called admin and password admin I log into database 
quickstart_live. When I try and use the same user details to log in via 
desktop it wont allow me it gives me the same error.



-- 
Mark Kinnear IChief Revenue Officer I National
*Kinnvest *
(o) 011 057-3652 (c) 063 098 8963
(e) mark@kinnvest.com (w) www.kinnvest.com
*"Dream,Believe & Achieve"**

*
This email and attachments are confidential and may be legally 
privileged or otherwise exempt from disclosure. If you are not the 
intended recipient, any unauthorized use, dissemination, distribution or 
reproduction of this message is strictly prohibited. If this e-mail is 
received in error, please delete immediately from your system 
*________________________________________________________________________________________________________________________________________________________________________________________________*

**Comment by gilmoskowitz** [comment]
Mark - Someone from our Operations group will contact you directly.
