### ISSUE TITLE
Login error from Mac Client 4.8.0 on Live 4.8.0 Db / Ubuntu 14.04 LTS

### ISSUE THREAD

**Issue by mperreault1980** [xtuple/xtuple-server#281]
I'm getting the following error when I try to login via remote: 

A System Error occurred at login2.cpp::429:
ERROR:  function login(boolean) does not exist
LINE 1: SELECT login(true) AS result, CURRENT_USER AS user;

Anyone know what could be causing this error?

log output: 
2015-03-06 17:32:55 UTC ERROR:  function login(boolean) does not exist at character 8
2015-03-06 17:32:55 UTC HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
2015-03-06 17:32:55 UTC STATEMENT:  SELECT login(true) AS result, CURRENT_USER AS user;

**Comment by gilmoskowitz** [comment]
@mperreault1980 - This usually means the you are connecting to a non-xTuple database. The second most common cause is that the restore of an xTuple database was incomplete. This might be related to the problems you had earlier finding the database to connect to. 

Check the Postgres error log, it should be in /var/logs/postgresql/..., for clues to distinguish between the 2 cases.

**Comment by mperreault1980** [comment]
The log output posted is from /var/log/postgresql/postgresql-9.3-postgresql-9.3-jmci-480-live.log which is the database in question. I'm using the web client to this database with no issues. Forgive me if I'm a complete newbie to this...

**Comment by gilmoskowitz** [comment]
Right... the messages above show the problem you see now.

I'm suggesting that you look earlier in the log for previous errors. A problem that occurred during the creation of the database might have been missed then and cause the login error you reported.

**Comment by mperreault1980** [comment]
Yeah there is a pile of errors... I'm guessing this is why I can't see my databases in the Webmin console. 

Here are some of the errors: 

2015-03-03 04:08:05 UTC ERROR:  schema "xt" does not exist
2015-03-03 04:08:05 UTC STATEMENT:  select xt.js_init(false);
2015-03-03 04:08:10 UTC WARNING:  Could not change ownership of public.pkghead to admin
2015-03-03 04:08:19 UTC WARNING:  column "act_action" has type "unknown"
2015-03-03 04:08:19 UTC DETAIL:  Proceeding with relation creation anyway.
2015-03-03 04:08:19 UTC CONTEXT:  SQL statement "create or replace view xt.act as select obj_uuid as act_uuid,obj_uuid::text as act_editor_key, acttype_code as act_type, todoitem_name as act_name, todoitem_active as act_
active, todoitem_status as act_status, todoitem_priority_id as act_priority_id, todoitem_description as act_description, todoitem_owner_username as act_owner_username, todoitem_username act_assigned_username, todoitem_st
art_date as act_start_date, todoitem_due_date as act_due_date, todoitem_assigned_date as act_assigned_date, todoitem_completed_date as act_completed_date, null::uuid as act_parent_uuid, null as act_action from public.tod
oitem join pg_class c on todoitem.tableoid = c.oid  join xt.acttype on acttype_tblname=relname "
	SQL statement "select xt.create_view('xt.act','select obj_uuid as act_uuid,obj_uuid::text as act_editor_key, acttype_code as act_type, todoitem_name as act_name, todoitem_active as act_active, todoitem_status as 
act_status, todoitem_priority_id as act_priority_id, todoitem_description as act_description, todoitem_owner_username as act_owner_username, todoitem_username act_assigned_username, todoitem_start_date as act_start_date,
 todoitem_due_date as act_due_date, todoitem_assigned_date as act_assigned_date, todoitem_completed_date as act_completed_date, null::uuid as act_parent_uuid, null as act_action from public.todoitem join pg_class c on to
doitem.tableoid = c.oid  join xt.acttype on acttype_tblname=relname ', true)"
2015-03-03 04:10:20 UTC ERROR:  handledError
2015-03-03 04:10:20 UTC DETAIL:  js_init() LINE 367:       throw "handledError";
2015-03-03 04:10:20 UTC STATEMENT:  select xt.get($${"nameSpace":"SYS","type":"User","id":"mperreault","username":"admin","encryptionKey":"c6a64741f43ab36402cf5a4d80ef3c632e5a53573b0652c40de5ed8abb8c48a2"}$$) as request
2015-03-03 04:45:32 UTC FATAL:  database "webmin" does not exist
2015-03-03 04:45:32 UTC FATAL:  database "webmin" does not exist
2015-03-03 05:40:11 UTC WARNING:  Error: The version being updated is not current.
	    at Object.XT.Data.updateRecord (eval at <anonymous> (js_init:921:20), <anonymous>:1280:14)
	    at Object.XT.Data.commitRecord (eval at <anonymous> (js_init:921:20), <anonymous>:947:14)
	    at Object.XT.Rest.patch (eval at <anonymous> (js_init:921:20), <anonymous>:187:12)
	    at patch:10:19
	    at null.<anonymous> (patch:1?
2015-03-03 05:40:11 UTC ERROR:  unhandledError
2015-03-03 05:40:11 UTC DETAIL:  js_init() LINE 373:       throw "unhandledError";
2015-03-03 05:40:11 UTC STATEMENT:  select xt.patch($${"nameSpace":"XM","type":"Contact","id":"5","etag":"ae96b897-584c-4d44-bdc4-2933ddb49dee","lock":{"effective":"2015-03-03T05:38:14.345Z","key":29,"username":"mperreau
lt"},"patches":[{"op":"replace","path":"/account","value":"2"}],"binaryField":null,"requery":false,"encoding":"rjson","username":"mperreault","encryptionKey":"c6a64741f43ab36402cf5a4d80ef3c632e5a53573b0652c40de5ed8abb8c4
8a2"}$$)
2015-03-03 05:53:52 UTC WARNING:  Error: Error: You do not have privileges to change this User Preference.
	    at Object.XT.Data.updateRecord (eval at <anonymous> (js_init:921:20), <anonymous>:1308:12)
	    at Object.XT.Data.commitRecord (eval at <anonymous> (js_init:921:20), <anonymous>:947:14)
	    at Object.XT.Rest.patch (eval at <anonymous> (js_init:921:20), <anonymous>:187:12)
	    at patch:10:19
	    at null.<anonymous> (patch:17:2)
	
2015-03-03 05:53:52 UTC ERROR:  unhandledError
2015-03-03 05:53:52 UTC DETAIL:  js_init() LINE 373:       throw "unhandledError";
2015-03-03 05:53:52 UTC STATEMENT:  select xt.patch($${"nameSpace":"XM","type":"UserAccount","id":"mperreault","lock":null,"patches":[{"op":"remove","path":"/grantedUserAccountRoles/0"}],"binaryField":null,"encoding":"rj
son","username":"mperreault","encryptionKey":"c6a64741f43ab36402cf5a4d80ef3c632e5a53573b0652c40de5ed8abb8c48a2"}$$)
2015-03-03 15:16:26 UTC WARNING:  Error: The version being updated is not current.
	    at Object.XT.Data.updateRecord (eval at <anonymous> (js_init:921:20), <anonymous>:1280:14)
	    at Object.XT.Data.commitRecord (eval at <anonymous> (js_init:921:20), <anonymous>:947:14)
	    at Object.XT.Rest.patch (eval at <anonymous> (js_init:921:20), <anonymous>:187:12)
	    at patch:10:19
	    at null.<anonymous> (patch:17:2)
	
2015-03-03 15:16:26 UTC ERROR:  unhandledError
2015-03-03 15:16:26 UTC DETAIL:  js_init() LINE 373:       throw "unhandledError";
2015-03-03 15:16:26 UTC STATEMENT:  select xt.patch($${"nameSpace":"XM","type":"Contact","id":"8","etag":"e8b7d577-71a5-41ed-e27d-0bd9dfd59f5a","lock":{"effective":"2015-03-03T15:15:45.314Z","key":45,"username":"mperreau
lt"},"patches":[{"op":"replace","path":"/account","value":"6"}],"binaryField":null,"requery":false,"encoding":"rjson","username":"mperreault","encryptionKey":"c6a64741f43ab36402cf5a4d80ef3c632e5a53573b0652c40de5ed8abb8c4
8a2"}$$)
2015-03-03 15:28:43 UTC FATAL:  database "logout" does not exist
2015-03-03 15:43:11 UTC WARNING:  Error: The version being updated is not current.
	    at Object.XT.Data.updateRecord (eval at <anonymous> (js_init:921:20), <anonymous>:1280:14)
	    at Object.XT.Data.commitRecord (eval at <anonymous> (js_init:921:20), <anonymous>:947:14)
	    at Object.XT.Rest.patch (eval at <anonymous> (js_init:921:20), <anonymous>:187:12)
	    at patch:10:19
	    at null.<anonymous> (patch:17:2)
	
2015-03-03 15:43:11 UTC ERROR:  unhandledError
2015-03-03 15:43:11 UTC DETAIL:  js_init() LINE 373:       throw "unhandledError";
2015-03-03 15:43:11 UTC STATEMENT:  select xt.patch($${"nameSpace":"XM","type":"Contact","id":"13","etag":"def7442a-ba9a-4d49-9b32-5bf58dfd64e1","lock":{"effective":"2015-03-03T15:42:25.394Z","key":55,"username":"mperrea
ult"},"patches":[{"op":"replace","path":"/account","value":"9"}],"binaryField":null,"requery":false,"encoding":"rjson","username":"mperreault","encryptionKey":"c6a64741f43ab36402cf5a4d80ef3c632e5a53573b0652c40de5ed8abb8c
48a2"}$$)
2015-03-03 16:25:31 UTC WARNING:  Error: new row for relation "prjtask" violates check constraint "prjtask_prjtask_status_check"
	    at Object.XT.Data.createRecord (eval at <anonymous> (js_init:921:20), <anonymous>:1000:20)
	    at Object.XT.Data.commitRecord (eval at <anonymous> (js_init:921:20), <anonymous>:944:14)
	    at Object.XT.Data.commitArrays (eval at <anonymous> (js_init:921:20), <anonymous>:878:18)
	    at Object.XT.Data.updateRecord (eval at <anonymous> (js_init:921:20), <anonymous>:1292:12)
	    at Object.XT.Data.commitRecord (eval at <anonymous> (js_init:921:20), <anonymous>:947:14)
	    at Object.XT.Rest.patch (eval at <anonymous> (js_init:921:20), <anonymous>:187:12)
	    at patch:10:19
	    at null.<anonymous> (patch:17:2)

**Comment by mperreault1980** [comment]
I think this answers a lot of questions, but i'm not experienced enough to tell for sure. Anytime I run the install, this is the result.... always permissions errors. Why would these happen:

useradd jmcinew -d /usr/local/jmcinew -p sWyML6s1
usermod -a -G postgres,xtuser jmcinew
chage -d 0 jmcinew
chown -R :xtuser /var/log/postgresql
chown -R jmcinew:xtuser /usr/local/jmcinew
chown -R jmcinew:xtuser /var/log/xtuple/jmcinew-480-live
chown -R jmcinew:xtuser /etc/xtuple/jmcinew-480-live
chown -R jmcinew:xtuser /var/lib/xtuple/jmcinew-480-live
chown -R jmcinew:xtuser /var/run/xtuple/jmcinew-480-live
chown -R jmcinew:ssl-cert /etc/xtuple/jmcinew-480-live/ssl
chown -R jmcinew:jmcinew /usr/local/jmcinew
chown -R jmcinew:jmcinew /usr/local/jmcinew/.xtuple
chmod -R u=rwx /usr/local/jmcinew
chmod -R u=rwx,g=wx /var/log/xtuple/jmcinew-480-live
chmod -R u=rwx,g=wx /var/log/postgresql
chmod -R u=rwx,g-rwx /var/lib/xtuple/jmcinew-480-live
chmod -R g=rx,u=wrx,o-rwx /etc/xtuple/jmcinew-480-live/ssl
chmod -R g=rwx,u=wrx,o-rw /etc/xtuple/jmcinew-480-live
n info pg.cluster Running...
n info cmd pg_createcluster 9.3 jmcinew-480-live --user jmcinew --socketdir /var/run/postgresql  --start
could not change directory to "/root": Permission denied
n info cmd sudo -u jmcinew pg_ctlcluster 9.3 jmcinew-480-live restart -m fast
could not change directory to "/root": Permission denied
n info cmd sudo -u jmcinew /usr/lib/postgresql/9.3/bin/createdb jmcinew -U jmcinew -O jmcinew -p 5435
could not change directory to "/root": Permission denied
n info cmd sudo -u jmcinew /usr/lib/postgresql/9.3/bin/psql  -U jmcinew -p 5435 -c "CREATE EXTENSION IF NOT EXISTS plv8;"
could not change directory to "/root": Permission denied
n info cmd sudo -u jmcinew /usr/lib/postgresql/9.3/bin/psql  -U jmcinew -p 5435 -c "CREATE EXTENSION IF NOT EXISTS plpgsql"
could not change directory to "/root": Permission denied
NOTICE:  extension "plpgsql" already exists, skipping
n info cmd sudo -u jmcinew /usr/lib/postgresql/9.3/bin/psql  -U jmcinew -p 5435 -c "CREATE EXTENSION IF NOT EXISTS hstore"
could not change directory to "/root": Permission denied
n info cmd sudo -u jmcinew /usr/lib/postgresql/9.3/bin/psql  -U jmcinew -p 5435 -c "CREATE ROLE admin WITH LOGIN PASSWORD 'admin' SUPERUSER"
could not change directory to "/root": Permission denied
n info cmd sudo -u jmcinew /usr/lib/postgresql/9.3/bin/psql  -U jmcinew -p 5435 -c "CREATE ROLE xtrole WITH ROLE admin"
could not change directory to "/root": Permission denied
n info cmd sudo -u jmcinew /usr/lib/postgresql/9.3/bin/psql  -U jmcinew -p 5435 -c "CREATE ROLE postgres LOGIN SUPERUSER"
could not change directory to "/root": Permission denied
n info cmd sudo -u jmcinew /usr/lib/postgresql/9.3/bin/psql  -U jmcinew -p 5435 -c "GRANT xtrole TO admin"
could not change directory to "/root": Permission denied
NOTICE:  role "admin" is already a member of role "xtrole"
n info cmd sudo -u jmcinew /usr/lib/postgresql/9.3/bin/psql  -U jmcinew -p 5435 -c "GRANT xtrole TO jmcinew"
could not change directory to "/root": Permission denied

**Comment by gilmoskowitz** [comment]
I have never seen the "permission denied" errors cause other problems but they are a bug.

There is still some vital piece of information missing to explain the original problem of the missing login() function. Did you say that you can use this database with the mobile web client?

**Comment by mperreault1980** [comment]
hi sorry about the delay in response. I can use this DB via the login at https://96.126.115.10:41212 without any issue. Have re-created the whole Ubuntu build and everything and still get the same problem.

**Comment by gilmoskowitz** [comment]
There's obviously something wrong with either the contents of the database that xtuple-server is starting with or the way that database is being installed. Let's try to figure out what's missing or strange or incorrect.

Create a plain text file (not a word processing document) with the following:

```SQL
select fetchMetricText('ServerVersion'), version();
show search_path;
select nspname from pg_namespace order by 1;
select nspname, proname
  from pg_namespace n join pg_proc p on n.oid=pronamespace
 where proname ~* 'login';
select public.login();
show search_path;
select pkghead_name, pkghead_version from public.pkghead order by 1;
select nspname, count(*) as NumberOfProcedures
  from pg_namespace n join pg_proc p on n.oid=pronamespace
 group by nspname order by nspname;
select nspname, count(distinct proname) as NumberOfProcedures
  from pg_namespace n join pg_proc p on n.oid=pronamespace
 group by nspname order by nspname;
select nspname, relkind, count(*) as NumberOfRelations
  from pg_namespace n join pg_class on n.oid=relnamespace
 group by nspname, relkind order by nspname, relkind;
```
Then run the following from a Terminal window on the Linux host and send us the output:

```
psql -e -U admin -p 5435 -d name-of-your-database -f name-of-your-file
```
If you paste the output into a comment on this issue please wrap it in a code block.

**Comment by mperreault1980** [comment]
Here's the output I got. I had to run it on port 5433 though. I hope I wrapped the code block right.


```
select fetchMetricText('ServerVersion'), version();
psql:getInfo:1: ERROR:  function fetchmetrictext(unknown) does not exist
LINE 1: select fetchMetricText('ServerVersion'), version();
               ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
show search_path;
  search_path   
----------------
 "$user",public
(1 row)

select nspname from pg_namespace order by 1;
      nspname       
--------------------
 information_schema
 pg_catalog
 pg_temp_1
 pg_toast
 pg_toast_temp_1
 public
(6 rows)

select nspname, proname
  from pg_namespace n join pg_proc p on n.oid=pronamespace
 where proname ~* 'login';
 nspname | proname 
---------+---------
(0 rows)

select public.login();
psql:getInfo:7: ERROR:  function public.login() does not exist
LINE 1: select public.login();
               ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
show search_path;
  search_path   
----------------
 "$user",public
(1 row)

select pkghead_name, pkghead_version from public.pkghead order by 1;
psql:getInfo:9: ERROR:  relation "public.pkghead" does not exist
LINE 1: select pkghead_name, pkghead_version from public.pkghead ord...
                                                  ^
select nspname, count(*) as NumberOfProcedures
  from pg_namespace n join pg_proc p on n.oid=pronamespace
 group by nspname order by nspname;
      nspname       | numberofprocedures 
--------------------+--------------------
 information_schema |                 12
 pg_catalog         |               2520
 public             |                 55
(3 rows)

select nspname, count(distinct proname) as NumberOfProcedures
  from pg_namespace n join pg_proc p on n.oid=pronamespace
 group by nspname order by nspname;
      nspname       | numberofprocedures 
--------------------+--------------------
 information_schema |                 12
 pg_catalog         |               2071
 public             |                 50
(3 rows)

select nspname, relkind, count(*) as NumberOfRelations
  from pg_namespace n join pg_class on n.oid=relnamespace
 group by nspname, relkind order by nspname, relkind;
      nspname       | relkind | numberofrelations 
--------------------+---------+-------------------
 information_schema | r       |                 7
 information_schema | v       |                59
 pg_catalog         | i       |                95
 pg_catalog         | r       |                51
 pg_catalog         | v       |                46
 pg_toast           | i       |                17
 pg_toast           | t       |                17
(7 rows)
```

**Comment by gilmoskowitz** [comment]
So... the database you connected to on port 5433 is not an xTuple database. There should be more schemas (at absolute minimum `api` and `xt`), more stored procedures (more than 1400 in `public`, more than 1100 distinct in `public`), and there should actually be tables in `public`.

Note that in one of the previous posts there are frequent references to a database server running on port 5435, like this line:
```
n info cmd sudo -u jmcinew /usr/lib/postgresql/9.3/bin/psql -U jmcinew -p 5435 -c "CREATE ROLE xtrole WITH ROLE admin"
```

The problem connecting with the desktop client appears to be that you're trying to connect either with the wrong database name, the wrong port number, or both.

**Comment by mperreault1980** [comment]
Makes sense, so what's wrong with the installation documentation then? I've tried this installation probably about 8 times and it hasn't worked properly once. Each time I have rebuilt new Ubuntu machines, so have started from scratch.

**Comment by mperreault1980** [comment]
Not sure if it makes a difference or not, but I'm using a hosted server on Linode. Would that make any difference? I would assume not.

**Comment by gilmoskowitz** [comment]
Using a hosted server probably doesn't make any difference.

The biggest problem with our documentation is really in the output of the `xtuple-server` command - it does not yet [display the name of the database it created](https://github.com/xtuple/xtuple-server/issues/279).

There is also non-determinism in the overall behavior which we are resolving one piece at a time. For some reason certain people have more problems running `xtuple-server` than other people, even with identical command lines on the same network, but on different machines.

**Comment by mperreault1980** [comment]
Ok. So what would you recommend for next steps? I'm getting chewed out for not having this up and running and just want to get it resolved.

**Comment by gilmoskowitz** [comment]
Look at the latest `xtuple-server` logfile. Get the host, port, and admin password from there.

```
psql -h hostaddr -p port -d template1 -U admin
Password: type-the-admin-password-here
\l
-- that's a backslash followed by lowercase letter L
-- and should print the names of all databases known to this server instance
```

Get the name of the pilot database from there and give it to the desktop client when you try to connect. Make sure to use the right hostaddr and port, too, of course.

The mobile client and webmin interface should also show the database name.

**Comment by mperreault1980** [comment]
Ok. Here's the output from that:

```
template1=# \l
                               List of databases
    Name    | Owner  | Encoding |   Collate   |    Ctype    | Access privileges 
------------+--------+----------+-------------+-------------+-------------------
 empty_live | admin  | UTF8     | en_US.UTF-8 | en_US.UTF-8 | 
 maggie     | maggie | UTF8     | en_US.UTF-8 | en_US.UTF-8 | 
 postgres   | maggie | UTF8     | en_US.UTF-8 | en_US.UTF-8 | 
 template0  | maggie | UTF8     | en_US.UTF-8 | en_US.UTF-8 | =c/maggie        +
            |        |          |             |             | maggie=CTc/maggie
 template1  | maggie | UTF8     | en_US.UTF-8 | en_US.UTF-8 | =c/maggie        +
            |        |          |             |             | maggie=CTc/maggie
(5 rows)

```

Which is it?

**Comment by mperreault1980** [comment]
i tried the empty_live one (the one that works on the web client) and I get in  but need to enter a registration key?

**Comment by gilmoskowitz** [comment]
JEEJT-CTWEJ-ZGY8Z-MXJZK-ECVCB is a single-user key you can use to get started

**Comment by mperreault1980** [comment]
ok. I thought this version was free to use? We only have three users, so what do I need for that?

**Comment by gilmoskowitz** [comment]
You can get a key by filling out the form at http://www.xtuple.org/webform/postbooks-license-renewal

**Comment by mperreault1980** [comment]
almost there! Got my multi-user key, but the Registration is greyed out in the system setup. Any idea how to get that enabled?

**Comment by gilmoskowitz** [comment]
Make sure you have the `MaintainRegistrationKey` privilege:

- **System** > **Maintain User Accounts** > `admin` > **Edit**
- select **Module** `System`
- if `MaintainRegistrationKey` is listed under **Available Privileges** (left-hand-side) then select it and **Add->**
- **Save**
- **System** > **Rescan Privileges**
- **System** > **Setup**

and check that **Registration** is enabled. If rescanning privileges doesn't work, try quitting and restarting the desktop client.

I'm going to close this issue since the initial problem of connecting with the desktop client has been solved.
