### ISSUE TITLE
Can't install xtuple-server

### ISSUE THREAD

**Issue by btcdream** [xtuple/xtuple-server#282]
root@iZ252tyl1niZ:~# npm -v
1.4.28
root@iZ252tyl1niZ:~# npm -v
1.4.28
root@iZ252tyl1niZ:~# node -v
v0.11.13
root@iZ252tyl1niZ:~# npm install -g xtuple-server
npm ERR! notsup Unsupported
npm ERR! notsup Not compatible with your operating system or architecture: xtuple-server@1.2.2
npm ERR! notsup Valid OS:    linux
npm ERR! notsup Valid Arch:  !ia32
npm ERR! notsup Actual OS:   linux
npm ERR! notsup Actual Arch: ia32

npm ERR! System Linux 3.13.0-32-generic
npm ERR! command "node" "/usr/local/bin/npm" "install" "-g" "xtuple-server"
npm ERR! cwd /root
npm ERR! node -v v0.11.13
npm ERR! npm -v 1.4.28
npm ERR! code EBADPLATFORM
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /root/npm-debug.log
npm ERR! not ok code 0

**Comment by davidbeauchamp** [comment]
Is that a 32bit install? xtuple-server will only install on 64bit machines

**Comment by btcdream** [comment]
@davidbeauchamp yes  you are right.I had  change  a  machines

root@iZ252tyl1niZ:~# uname -a 
Linux iZ252tyl1niZ 3.13.0-32-generic #57-Ubuntu SMP Tue Jul 15 03:51:08 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
root@iZ252tyl1niZ:~# npm install -g xtuple-server
\
> xtuple-server@1.2.2 preinstall /usr/local/lib/node_modules/xtuple-server
> nex do engines

nex info do engines
nex info loading module nex-engines
nex ERR! do engines Cannot find module 'nex-engines'
nex info debug See nex-debug.log for more info
/usr/local/bin/xtupled -> /usr/local/lib/node_modules/xtuple-server/tasks/sys/service/cli.js

> xtuple-server@1.2.2 postinstall /usr/local/lib/node_modules/xtuple-server
> nex do

nex info do engines
nex info loading module nex-engines
nex ERR! do undefined 'Cannot find module \'nex-engines\''
nex info debug See nex-debug.log for more info
xtuple-server@1.2.2 /usr/local/lib/node_modules/xtuple-server
鈹溾攢鈹€ cp@0.1.1
鈹溾攢鈹€ rimraf@2.3.2
鈹溾攢鈹€ requireindex@1.1.0
鈹溾攢鈹€ lodash@2.4.1
鈹溾攢鈹€ github-latest@0.1.2 (semver@1.1.4)
鈹溾攢鈹€ mkdirp@0.5.0 (minimist@0.0.8)
鈹溾攢鈹€ npmlog@0.1.1 (ansi@0.3.0)
鈹溾攢鈹€ pgrep@0.0.5 (bluebird@2.9.14)
鈹溾攢鈹€ glob@4.5.2 (inherits@2.0.1, once@1.3.1, inflight@1.0.4, minimatch@2.0.3)
鈹斺攢鈹€ xtuple-server-lib@1.2.0 (cron-tab@1.1.16, semver@2.3.2, moment@2.9.0, node-latest-version@1.0.15)

**Comment by btcdream** [comment]
I had  solved it
adduser newuser ,then  run it  as  newuser.
